<?php

  $CHANGE_NIVEAU = -1;
  $CHANGE_ANNEE = -2;
  $CHANGE_DOMAINE = -3;
  $CHANGE_MENTION = -4;
  $CHANGE_SPECIALITE = -5;
  $CHANGE_PARCOURS = -6;
  $CHANGE_POLE = -7;
  $CHANGE_OPTION = -8;
  $CHANGE_GROUPE = -9;

?>